### ISSUE TITLE
Logged Exception, no cache.lock file created

### ISSUE THREAD

**Issue by Krutoy242** [EnderExtreme/Thaumic-Speedup#2]
After update `2.0` => `3.0` version, i removed `cache.lock` file, but new one didn't created when i lunched game.

I found this lines in debug.log file:

```less
[21:41:11] [ThaumicSpeedup/AspectThread/ERROR] [FML]: Exception caught during firing event thaumcraft.api.aspects.AspectRegistryEvent@51ffec23:
java.util.ConcurrentModificationException: null
	at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:401) ~[guava-21.0.jar:?]
	at java.util.Collections$UnmodifiableCollection$1.hasNext(Collections.java:1041) ~[?:1.8.0_51]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes(ThaumcraftCraftingManager.java:500) ~[ThaumcraftCraftingManager.class:?]
[...]
	at thaumcraft.api.aspects.AspectEventProxy.registerComplexObjectTag(AspectEventProxy.java:55) ~[AspectEventProxy.class:?]
	at vazkii.botania.common.integration.thaumcraft.TCAspects.registerComplex(TCAspects.java:472) ~[TCAspects.class:?]
```

Modpack: https://github.com/Krutoy242/Enigmatica2Expert-Extended

Is this means Thaumic-Speedup uncompatible with some mods? Should i return to `2.0` version?

[debug.log](https://github.com/LoliKingdom/Thaumic-Speedup/files/7788876/debug.zip)

**Comment by Rongmario** [comment]
`cache.lock` no longer is needed. I'll fix that bug though, it seems like mods that use the event to register aspects ends up bugging out.

**Comment by Krutoy242** [comment]
> cache.lock no longer is needed

So, where cached file stored? I want to supply it with modpack files, so players would have fast first load.

**Comment by Rongmario** [comment]
`.minecraft/caches/thaumicspeedup/aspects_cache.bin`

**Comment by Krutoy242** [comment]
There is no such file:
![](https://i.imgur.com/iKfZg3y.png)

So, i don't get it right: is mod not working right now because of this exception?

**Comment by Rongmario** [comment]
Possibly, do you have Persistency installed?

**Comment by Krutoy242** [comment]
> Possibly, do you have Persistency installed?

Yes, i do. 
Its also listed in mod list in `debug.log` from zero post.

**Comment by Rongmario** [comment]
Fixed now @Krutoy242.
